format = """\
[](bg:#170309 fg:#170309)\
[󰀵 ](bg:#170309 fg:#F9215D)\
[](fg:#170309 bg:#F9215D)\
$time\
[](fg:#F9215D bg:#170309)\
$directory\
[](fg:#170309 bg:#F9215D)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#F9215D bg:#170309)\
$character\
"""

[directory]
format = "[  $path ]($style)"
style = "fg:#F9215D bg:#170309"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#170309 bg:#F9215D"

[git_status]
format = '[$all_status]($style)'
style = "fg:#170309 bg:#F9215D"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#170309 bg:#F9215D"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](#F9215D) '
error_symbol = '[ ✗](#f14c4c) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#170309"
format = '[[ 󱑍 $time ](bg:#F9215D fg:#170309)]($style)'
